from .welcome_scene import *
from .dining_empty_scene import *
from .dining_customer_scene import *
from .ordering_scene import *
from .kitchen_scene import *
from .kitchen_order_scene import *
from .results_scene import *
from .ending_scene import *
from .credits_scene import *
